-- Create wallets table
-- This table stores wallet information including invisible (platform-generated) and external (user-connected) wallets
CREATE TABLE wallets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  address TEXT NOT NULL UNIQUE,
  encrypted_private_key TEXT,
  type TEXT NOT NULL CHECK (type IN ('invisible', 'external')),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX idx_wallets_user_id ON wallets(user_id);
CREATE INDEX idx_wallets_address ON wallets(address);

-- Add comments for documentation
COMMENT ON TABLE wallets IS 'Stores wallet information including invisible (platform-generated) and external (user-connected) wallets';
COMMENT ON COLUMN wallets.encrypted_private_key IS 'AES-256-GCM encrypted private key, only populated for invisible wallets';
COMMENT ON COLUMN wallets.type IS 'invisible: generated by platform, external: user-connected wallet';
